runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /jspsych-6.1.0
  static_dir: jspsych-6.1.0

- url: /debrief
  static_dir: debrief

- url: /.*
  script: backend.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

builtins:
  - remote_api: on
